name: Študentská komora Akademického senátu FMFI UK
description: Oficiálna stránka Študentskej komory Akademického senátu FMFI UK
url: http://skas.fmph.uniba.sk

rss_feed_limit: 10

paginate: 5
paginate_path: "strana:num"

markdown: kramdown #redcarpet
pygments: true

kramdown:
    toc_levels: 1..3
    #transliterated_header_ids: true
